@extends('layouts.recruiter')
@section('title', $profile->user->name)
@section('content')
<a class="account-back" href="{{ route('recruiter.talent.index') }}"><i class="bi bi-arrow-left"></i> Back to talent</a>
<div class="dashboard-heading mt-3"><div><span class="dashboard-kicker">FULL TALENT PROFILE</span><h1>{{ $profile->user->name }}</h1><p>{{ $profile->headline ?: 'Available candidate' }}</p></div></div>
@if(session('status'))<div class="alert alert-success">{{ session('status') }}</div>@endif @if($errors->any())<div class="alert alert-danger">{{ $errors->first() }}</div>@endif
<div class="row g-3"><div class="col-xl-8"><section class="dashboard-card mb-3"><div class="card-heading"><div><span>SUMMARY</span><h2>Professional overview</h2></div></div><p>{{ $profile->professional_summary ?: $profile->career_objective ?: 'No summary provided.' }}</p><div class="candidate-tags">@foreach($profile->skills as $skill)<small>{{ $skill->display_name }}</small>@endforeach</div></section><section class="dashboard-card"><div class="card-heading"><div><span>BACKGROUND</span><h2>Experience and education</h2></div></div>@forelse($profile->experiences as $experience)<div class="profile-record"><div><strong>{{ $experience->designation }}</strong><span>{{ $experience->organization_name }}</span></div><small>{{ $experience->started_on }} — {{ $experience->ended_on ?: 'Present' }}</small></div>@empty<p class="text-muted">No experience added.</p>@endforelse @foreach($profile->educations as $education)<div class="profile-record"><div><strong>{{ $education->degree_name }}</strong><span>{{ $education->institution_name }}</span></div><small>{{ $education->passing_year }}</small></div>@endforeach</section></div>
<div class="col-xl-4"><section class="dashboard-card mb-3"><div class="card-heading"><div><span>CONTACT</span><h2>Contact details</h2></div></div>@if($canViewContact)<p><i class="bi bi-envelope me-2"></i>{{ $profile->email_allowed ? ($profile->alternate_email ?: $profile->user->email) : 'Candidate has disabled email contact' }}</p><p><i class="bi bi-phone me-2"></i>{{ $profile->sms_allowed ? ($profile->mobile ?: 'Not provided') : 'Candidate has disabled phone contact' }}</p><p><i class="bi bi-whatsapp me-2"></i>{{ $profile->whatsapp_allowed ? ($profile->whatsapp ?: 'Not provided') : 'Candidate has disabled WhatsApp contact' }}</p><p><i class="bi bi-linkedin me-2"></i>{{ $profile->linkedin_url ?: 'Not provided' }}</p>@else<div class="account-empty"><i class="bi bi-lock"></i><strong>Contact details are protected</strong><span>Move “Talent contact details” to your plan or upgrade.</span></div>@endif</section>
@if(! $candidateCanReceive)<section class="dashboard-card"><div class="account-empty"><i class="bi bi-inbox"></i><strong>Communications unavailable</strong><span>This candidate’s current plan does not receive recruiter messages or interview invitations.</span></div></section>@elseif($canMessage || $canInvite)<section class="dashboard-card"><div class="card-heading"><div><span>OUTREACH</span><h2>Contact in portal</h2></div></div><form method="POST" action="{{ route('recruiter.talent.contact', $profile) }}">@csrf <label class="form-label">Type</label><select class="form-select" name="type">@if($canMessage)<option value="message">Opportunity message</option>@endif @if($canInvite)<option value="interview">Interview invitation</option>@endif</select><label class="form-label mt-2">Subject</label><input class="form-control" name="subject" required><label class="form-label mt-2">Message</label><textarea class="form-control" name="message" rows="4" required></textarea>@if($canInvite)<label class="form-label mt-2">Interview date & time</label><input class="form-control" type="datetime-local" name="scheduled_at"><label class="form-label mt-2">Meeting link or location</label><input class="form-control" name="meeting_location">@endif<button class="btn btn-portal w-100 mt-3" type="submit"><i class="bi bi-send"></i> Send</button></form></section>@endif</div></div>
@endsection
