@extends('layouts.talent')
@section('title', $tabs[$tab].' · Candidate Profile')
@section('content')
<div class="dashboard-heading"><div><span class="dashboard-kicker">CANDIDATE PROFILE · {{ $profile->profile_code }}</span><h1>{{ $tabs[$tab] }}</h1><p>Build a verified, searchable profile recruiters can understand quickly.</p></div></div>
@if(session('status'))<div class="alert alert-success">{{ session('status') }}</div>@endif
@if($errors->any())<div class="alert alert-danger"><ul class="mb-0">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif

@if($tab==='photograph') @include('talent.profile.photograph')
@elseif(in_array($tab,['personal','contact','preferences']))<form method="POST" action="{{ route('talent.profile.update',$tab) }}">@csrf @method('PUT')<section class="dashboard-card profile-form-card"><div class="profile-form-grid">
@if($tab==='personal')
<div><label class="form-label">First name</label><input class="form-control" name="first_name" value="{{ old('first_name',$profile->first_name) }}" required></div><div><label class="form-label">Middle name</label><input class="form-control" name="middle_name" value="{{ old('middle_name',$profile->middle_name) }}"></div><div><label class="form-label">Last name</label><input class="form-control" name="last_name" value="{{ old('last_name',$profile->last_name) }}" required></div><div><label class="form-label">Date of birth</label><input class="form-control" type="date" name="date_of_birth" value="{{ old('date_of_birth',$profile->date_of_birth?->format('Y-m-d')) }}"></div>
@include('talent.profile.master-select',['name'=>'gender_id','label'=>'Gender','items'=>$genders,'value'=>$profile->gender_id]) @include('talent.profile.master-select',['name'=>'marital_status_id','label'=>'Marital status','items'=>$maritalStatuses,'value'=>$profile->marital_status_id]) @include('talent.profile.master-select',['name'=>'nationality_country_id','label'=>'Nationality','items'=>$countries,'value'=>$profile->nationality_country_id])
<div class="profile-span"><label class="form-label">Professional headline</label><input class="form-control" name="headline" value="{{ old('headline',$profile->headline) }}" placeholder="e.g. Laravel developer with 4 years’ experience"></div><div class="profile-span"><label class="form-label">Career objective</label><textarea class="form-control" name="career_objective" rows="3">{{ old('career_objective',$profile->career_objective) }}</textarea></div><div class="profile-span"><label class="form-label">Professional summary</label><textarea class="form-control" name="professional_summary" rows="5">{{ old('professional_summary',$profile->professional_summary) }}</textarea></div>@include('talent.profile.switch',['name'=>'is_public','label'=>'Allow recruiters to discover my profile','checked'=>$profile->is_public])
@elseif($tab==='contact')
@foreach([['mobile','Mobile'],['whatsapp','WhatsApp'],['alternate_email','Alternate email'],['linkedin_url','LinkedIn URL'],['portfolio_url','Portfolio URL'],['address_line_1','Address line 1'],['address_line_2','Address line 2'],['city','City / Town'],['state','State / Province'],['postal_code','Postal code']] as [$name,$label])<div><label class="form-label">{{ $label }}</label><input class="form-control" name="{{ $name }}" value="{{ old($name,$profile->$name) }}"></div>@endforeach @include('talent.profile.master-select',['name'=>'country_id','label'=>'Country','items'=>$countries,'value'=>$profile->country_id])<div class="profile-span profile-switches">@foreach([['email_allowed','Email allowed'],['sms_allowed','SMS allowed'],['whatsapp_allowed','WhatsApp allowed'],['job_alerts_allowed','Job alerts']] as [$name,$label])@include('talent.profile.switch',['name'=>$name,'label'=>$label,'checked'=>$profile->$name])@endforeach</div>
@else
<div><label class="form-label">Availability</label><select class="form-select" name="availability_status"><option value="">Select</option>@foreach(['available'=>'Available','employed'=>'Employed','not-looking'=>'Not looking'] as $v=>$l)<option value="{{ $v }}" @selected($profile->availability_status===$v)>{{ $l }}</option>@endforeach</select></div><div><label class="form-label">Available from</label><input class="form-control" type="date" name="available_from" value="{{ $profile->available_from?->format('Y-m-d') }}"></div><div><label class="form-label">Expected salary minimum</label><input class="form-control" type="number" min="0" name="expected_salary_min" value="{{ $profile->expected_salary_min }}"></div><div><label class="form-label">Expected salary maximum</label><input class="form-control" type="number" min="0" name="expected_salary_max" value="{{ $profile->expected_salary_max }}"></div><div><label class="form-label">Employment types</label>@foreach($employmentTypes as $item)<label class="form-check"><input class="form-check-input" type="checkbox" name="employment_types[]" value="{{ $item->id }}" @checked($profile->employmentTypes->contains($item))>{{ $item->display_name }}</label>@endforeach</div><div><label class="form-label">Work modes</label>@foreach($workModes as $item)<label class="form-check"><input class="form-check-input" type="checkbox" name="work_modes[]" value="{{ $item->id }}" @checked($profile->workModes->contains($item))>{{ $item->display_name }}</label>@endforeach</div>@include('talent.profile.switch',['name'=>'willing_to_relocate','label'=>'Willing to relocate','checked'=>$profile->willing_to_relocate]) @include('talent.profile.switch',['name'=>'willing_to_travel','label'=>'Willing to travel','checked'=>$profile->willing_to_travel])
@endif
</div><button class="btn btn-portal mt-4" type="submit"><i class="bi bi-check-lg"></i>Save {{ Str::lower($tabs[$tab]) }}</button></section></form>
@elseif($tab==='education') @include('talent.profile.repeatable',['kind'=>'education','records'=>$profile->educations])
@elseif($tab==='experience') @include('talent.profile.repeatable',['kind'=>'experience','records'=>$profile->experiences])
@elseif($tab==='projects') @include('talent.profile.projects',['records'=>$profile->projects])
@elseif($tab==='recognitions') @include('talent.profile.recognitions',['records'=>$profile->recognitions])
@elseif($tab==='memberships') @include('talent.profile.memberships',['records'=>$profile->professionalMemberships])
@elseif($tab==='references') @include('talent.profile.references',['records'=>$profile->references])
@elseif($tab==='social') @include('talent.profile.social-profiles',['records'=>$profile->socialProfiles])
@elseif($tab==='declarations') @include('talent.profile.declarations')
@elseif($tab==='publications') @include('talent.profile.publications',['records'=>$profile->publications])
@elseif($tab==='talents') @include('talent.profile.talents',['records'=>$profile->talents])
@elseif($tab==='hobbies') @include('talent.profile.hobbies',['records'=>$profile->hobbies])
@else @include('talent.profile.skills')
@endif
@endsection
