@if($kind==='education')
<div class="education-stack">
    <section class="dashboard-card education-form-card"><div class="card-heading"><div><span>ACADEMIC RECORD</span><h2>Add education</h2></div></div>
        <form method="POST" action="{{ route('talent.profile.education') }}">@csrf<div class="profile-form-grid">
            @include('talent.profile.master-select',['name'=>'qualification_level_id','label'=>'Qualification level','items'=>$qualificationLevels,'value'=>null])
            <div><label class="form-label" for="degree_id">Degree / course</label><select class="form-select" id="degree_id" name="degree_id" data-degree-select data-placeholder="Search degree or course" required disabled><option value="">Select qualification level first</option>@foreach($degrees as $degree)<option value="{{ $degree->id }}" data-qualification-level="{{ $degree->qualification_level_id }}" @selected(old('degree_id')==$degree->id)>{{ $degree->display_name }}</option>@endforeach</select><div class="form-text">Options depend on the qualification level.</div></div><div><label class="form-label">Specialization / main subject</label><input class="form-control" name="specialization"></div>@include('talent.profile.master-select',['name'=>'educational_institution_id','label'=>'Educational institution','items'=>$educationalInstitutions,'value'=>null]) @include('talent.profile.master-select',['name'=>'education_authority_id','label'=>'Board / University','items'=>$educationAuthorities,'value'=>null])
            @include('talent.profile.master-select',['name'=>'country_id','label'=>'Country','items'=>$countries,'value'=>null]) @include('talent.profile.master-select',['name'=>'study_mode_id','label'=>'Study mode','items'=>$studyModes,'value'=>null])
            <div><label class="form-label">Start year</label><input class="form-control" type="number" name="start_year"></div><div><label class="form-label">Passing year</label><input class="form-control" type="number" name="passing_year"></div><div><label class="form-label">Result</label><input class="form-control" name="result" placeholder="Percentage, CGPA or grade"></div>@include('talent.profile.switch',['name'=>'currently_studying','label'=>'Currently studying','checked'=>false])
            <div class="profile-span education-subjects" data-new-education-subjects><label class="form-label">Subjects studied</label><select class="form-select" data-new-subject-select data-placeholder="Search and add subjects"><option value="">Click to select a subject</option>@foreach($subjects as $subject)<option value="{{ $subject->id }}">{{ $subject->display_name }}</option>@endforeach</select><div class="subject-chips" data-new-subject-chips></div><small class="subject-status">Select one or more subjects. Click × to remove one before saving.</small></div>
        </div><button class="btn btn-portal mt-3"><i class="bi bi-plus-lg"></i>Add education</button></form>
    </section>
    <section class="dashboard-card"><div class="card-heading"><div><span>EDUCATION HISTORY</span><h2>Added education</h2></div><span class="badge text-bg-light">{{ $records->count() }}</span></div>
        <div class="table-responsive"><table class="table align-middle education-table"><thead><tr><th>Qualification</th><th>Institution</th><th>Period & result</th><th>Subjects studied</th><th></th></tr></thead><tbody>
        @forelse($records as $record)<tr><td><strong>{{ $record->degree_name }}</strong><small>{{ $record->qualificationLevel?->display_name }}@if($record->specialization) · {{ $record->specialization }}@endif</small></td><td><strong>{{ $record->institution_name }}</strong><small>{{ $record->board_university }}</small></td><td><span>{{ $record->start_year ?: '—' }} – {{ $record->currently_studying ? 'Present' : ($record->passing_year ?: '—') }}</span><small>{{ $record->result }}</small></td><td><div class="subject-chips table-subject-chips" data-saved-subject-chips data-delete-url="{{ route('talent.profile.education.subjects.destroy',[$record,'__SUBJECT__']) }}">@forelse($record->subjects as $subject)<span class="subject-chip" data-subject-id="{{ $subject->id }}">{{ $subject->display_name }}<button type="button" data-remove-saved-subject aria-label="Remove {{ $subject->display_name }}">×</button></span>@empty<span class="text-secondary">No subjects selected</span>@endforelse</div></td><td class="text-end"><form method="POST" action="{{ route('talent.profile.remove',['education',$record]) }}" onsubmit="return confirm('Delete this education record?')">@csrf @method('DELETE')<button class="btn btn-sm btn-outline-danger" title="Delete education"><i class="bi bi-trash"></i></button></form></td></tr>
        @empty<tr><td colspan="5" class="text-center text-secondary py-4">No education added yet.</td></tr>@endforelse
        </tbody></table></div>
    </section>
</div>
@else
<div class="profile-record-grid"><section class="dashboard-card"><h2>Experience</h2>@forelse($records as $record)<div class="profile-record"><div><strong>{{ $record->designation }}</strong><span>{{ $record->organization_name }}</span></div><form method="POST" action="{{ route('talent.profile.remove',['experience',$record]) }}">@csrf @method('DELETE')<button class="btn btn-sm btn-outline-danger"><i class="bi bi-trash"></i></button></form></div>@empty<p class="text-secondary">No experience added yet.</p>@endforelse</section>
<section class="dashboard-card"><h2>Add experience</h2><form method="POST" action="{{ route('talent.profile.experience') }}">@csrf<div class="profile-form-grid"><div><label class="form-label">Organization</label><input class="form-control" name="organization_name" required></div><div><label class="form-label">Designation</label><input class="form-control" name="designation" required></div>@include('talent.profile.master-select',['name'=>'employment_type_id','label'=>'Employment type','items'=>$employmentTypes,'value'=>null]) @include('talent.profile.master-select',['name'=>'work_mode_id','label'=>'Work mode','items'=>$workModes,'value'=>null]) @include('talent.profile.master-select',['name'=>'country_id','label'=>'Country','items'=>$countries,'value'=>null])<div><label class="form-label">City</label><input class="form-control" name="city"></div><div><label class="form-label">Started on</label><input class="form-control" type="date" name="started_on" required></div><div><label class="form-label">Ended on</label><input class="form-control" type="date" name="ended_on"></div><div class="profile-span"><label class="form-label">Description</label><textarea class="form-control" name="description"></textarea></div>@include('talent.profile.switch',['name'=>'currently_working','label'=>'I currently work here','checked'=>false])</div><button class="btn btn-portal mt-3">Add experience</button></form></section></div>
@endif
