@extends('layouts.administrator')
@section('title','Company Profile')
@section('content')
<div class="dashboard-heading"><div><span class="dashboard-kicker">OWNER ORGANIZATION</span><h1>Company profile</h1><p>Manage the identity, contact information, branding, legal details, and promotional content used throughout the portal.</p></div><a class="btn btn-portal-light" href="{{ route('home') }}" target="_blank"><i class="bi bi-box-arrow-up-right"></i> Preview public site</a></div>
@if(session('status'))<div class="alert alert-success">{{ session('status') }}</div>@endif
@if($errors->any())<div class="alert alert-danger">{{ $errors->first() }}</div>@endif
<form method="POST" action="{{ route('admin.company.update') }}" enctype="multipart/form-data">@csrf @method('PUT')
<div class="company-settings-grid"><div>
<section class="dashboard-card mb-4"><div class="card-heading"><div><span>PUBLIC IDENTITY</span><h2>Name and story</h2></div></div><div class="profile-form-grid">
<div><label class="form-label">Display / brand name *</label><input class="form-control" name="display_name" required value="{{ old('display_name',$company->display_name) }}"></div><div><label class="form-label">Registered legal name</label><input class="form-control" name="legal_name" value="{{ old('legal_name',$company->legal_name) }}"></div><div class="profile-span"><label class="form-label">Tagline</label><input class="form-control" name="tagline" value="{{ old('tagline',$company->tagline) }}" placeholder="A short memorable promise"></div><div class="profile-span"><label class="form-label">Short description</label><textarea class="form-control" name="short_description" rows="2">{{ old('short_description',$company->short_description) }}</textarea></div><div class="profile-span"><label class="form-label">About the company</label><textarea class="form-control" name="about" rows="5">{{ old('about',$company->about) }}</textarea></div><div><label class="form-label">Mission</label><textarea class="form-control" name="mission" rows="4">{{ old('mission',$company->mission) }}</textarea></div><div><label class="form-label">Vision</label><textarea class="form-control" name="vision" rows="4">{{ old('vision',$company->vision) }}</textarea></div><div class="profile-span"><label class="form-label">Values</label><textarea class="form-control" name="values" rows="3" placeholder="One per line or a concise paragraph">{{ old('values',$company->values) }}</textarea></div></div></section>
<section class="dashboard-card mb-4"><div class="card-heading"><div><span>CONTACT & LOCATION</span><h2>How people reach you</h2></div></div><div class="profile-form-grid"><div><label class="form-label">Public email</label><input class="form-control" type="email" name="email" value="{{ old('email',$company->email) }}"></div><div><label class="form-label">Support email</label><input class="form-control" type="email" name="support_email" value="{{ old('support_email',$company->support_email) }}"></div><div><label class="form-label">Phone</label><input class="form-control" name="phone" value="{{ old('phone',$company->phone) }}"></div><div><label class="form-label">WhatsApp</label><input class="form-control" name="whatsapp" value="{{ old('whatsapp',$company->whatsapp) }}"></div><div class="profile-span"><label class="form-label">Website</label><input class="form-control" type="url" name="website" value="{{ old('website',$company->website) }}" placeholder="https://"></div><div><label class="form-label">Address line 1</label><input class="form-control" name="address_line_1" value="{{ old('address_line_1',$company->address_line_1) }}"></div><div><label class="form-label">Address line 2</label><input class="form-control" name="address_line_2" value="{{ old('address_line_2',$company->address_line_2) }}"></div><div><label class="form-label">City</label><input class="form-control" name="city" value="{{ old('city',$company->city) }}"></div><div><label class="form-label">State / province</label><input class="form-control" name="state" value="{{ old('state',$company->state) }}"></div><div><label class="form-label">Postal code</label><input class="form-control" name="postal_code" value="{{ old('postal_code',$company->postal_code) }}"></div><div><label class="form-label">Country</label><input class="form-control" name="country" value="{{ old('country',$company->country) }}"></div></div></section>
<section class="dashboard-card"><div class="card-heading"><div><span>DISCOVERY & PROMOTION</span><h2>SEO, social, and campaign content</h2></div></div><div class="profile-form-grid">@foreach(['facebook'=>'Facebook','instagram'=>'Instagram','linkedin'=>'LinkedIn','x'=>'X / Twitter','youtube'=>'YouTube'] as $key=>$label)<div><label class="form-label">{{ $label }} URL</label><input class="form-control" type="url" name="social_links[{{ $key }}]" value="{{ old('social_links.'.$key,$company->social_links[$key]??'') }}"></div>@endforeach<div><label class="form-label">SEO title</label><input class="form-control" name="meta_title" maxlength="70" value="{{ old('meta_title',$company->meta_title) }}"></div><div class="profile-span"><label class="form-label">SEO description</label><textarea class="form-control" name="meta_description" maxlength="170" rows="2">{{ old('meta_description',$company->meta_description) }}</textarea></div><div class="profile-span"><label class="form-label">SEO keywords</label><input class="form-control" name="meta_keywords" value="{{ old('meta_keywords',$company->meta_keywords) }}"></div><div class="profile-span form-check form-switch"><input type="hidden" name="promotion_enabled" value="0"><input class="form-check-input" id="promotion-enabled" type="checkbox" name="promotion_enabled" value="1" @checked(old('promotion_enabled',$company->promotion_enabled))><label class="form-check-label" for="promotion-enabled">Show promotional call-to-action</label></div><div><label class="form-label">Promotion heading</label><input class="form-control" name="promotion_heading" value="{{ old('promotion_heading',$company->promotion_heading) }}"></div><div><label class="form-label">Button label</label><input class="form-control" name="promotion_cta_label" value="{{ old('promotion_cta_label',$company->promotion_cta_label) }}"></div><div class="profile-span"><label class="form-label">Promotion message</label><textarea class="form-control" name="promotion_text" rows="2">{{ old('promotion_text',$company->promotion_text) }}</textarea></div><div class="profile-span"><label class="form-label">Promotion button URL</label><input class="form-control" type="url" name="promotion_cta_url" value="{{ old('promotion_cta_url',$company->promotion_cta_url) }}"></div></div></section>
</div><aside>
<section class="dashboard-card company-brand-card"><div class="card-heading"><div><span>BRAND ASSETS</span><h2>Logos and imagery</h2></div></div>@foreach([['logo','Primary logo',$company->logo_path],['logo_dark','Logo for dark backgrounds',$company->logo_dark_path],['favicon','Browser favicon',$company->favicon_path],['cover','Company cover / promotional image',$company->cover_path]] as [$key,$label,$path])<div class="company-upload"><label class="form-label">{{ $label }}</label>@if($path)<img src="{{ asset('storage/'.$path) }}" alt="{{ $label }}">@endif<input class="form-control" type="file" name="{{ $key }}" accept="image/*"><small>Upload a PNG, JPG, WebP{{ $key!=='favicon' ? ' or SVG':'' }}.</small></div>@endforeach</section>
<section class="dashboard-card mt-4"><div class="card-heading"><div><span>LEGAL PROFILE</span><h2>Registration details</h2></div></div><label class="form-label">Registration number</label><input class="form-control" name="registration_number" value="{{ old('registration_number',$company->registration_number) }}"><label class="form-label mt-3">Tax / VAT / GST number</label><input class="form-control" name="tax_number" value="{{ old('tax_number',$company->tax_number) }}"><label class="form-label mt-3">Founded on</label><input class="form-control" type="date" name="founded_on" value="{{ old('founded_on',$company->founded_on?->format('Y-m-d')) }}"><label class="form-label mt-3">Industry</label><input class="form-control" name="industry" value="{{ old('industry',$company->industry) }}"><label class="form-label mt-3">Company size</label><input class="form-control" name="company_size" value="{{ old('company_size',$company->company_size) }}" placeholder="e.g. 51–200 employees"></section>
</aside></div><div class="permission-savebar"><span><i class="bi bi-buildings"></i>Brand changes appear throughout the portal after saving.</span><button class="btn btn-portal" type="submit"><i class="bi bi-check2-circle"></i> Save company profile</button></div></form>
@endsection
