@extends('layouts.administrator')
@section('title','Payment Settings')
@section('content')
<div class="dashboard-heading"><div><span class="dashboard-kicker">BILLING & PAYMENTS</span><h1>Payment gateways</h1><p>Configure online payment providers, accepted methods, fees, limits, currencies, and webhook security.</p></div><a class="btn btn-portal-light" href="{{ route('admin.payments.transactions') }}"><i class="bi bi-receipt"></i> Transactions</a></div>
@if(session('status'))<div class="alert alert-success">{{ session('status') }}</div>@endif
@if($errors->any())<div class="alert alert-danger">{{ $errors->first() }}</div>@endif
<div class="payment-gateway-grid">
@foreach($gateways as $gateway)
@php($credentialFields=match($gateway->provider){'stripe'=>['publishable_key'=>'Publishable key','secret_key'=>'Secret key'],'paypal'=>['client_id'=>'Client ID','client_secret'=>'Client secret'],'razorpay'=>['key_id'=>'Key ID','key_secret'=>'Key secret'],'bank_transfer'=>['account_name'=>'Account name','bank_name'=>'Bank name','account_number'=>'Account number','routing_code'=>'Routing / SWIFT code'],default=>[]})
<form class="dashboard-card payment-gateway-card" method="POST" action="{{ route('admin.payments.update',$gateway) }}">@csrf @method('PUT')
<div class="card-heading"><div><span>{{ strtoupper($gateway->provider) }}</span><h2>{{ $gateway->name }}</h2></div><span class="account-status account-status--{{ $gateway->is_enabled ? 'active':'archived' }}"><i></i>{{ $gateway->is_enabled?'Enabled':'Disabled' }}</span></div>
<div class="gateway-switches"><div class="form-check form-switch"><input type="hidden" name="is_enabled" value="0"><input class="form-check-input" id="enabled-{{ $gateway->id }}" type="checkbox" name="is_enabled" value="1" @checked($gateway->is_enabled)><label class="form-check-label" for="enabled-{{ $gateway->id }}">Accept payments</label></div><div class="form-check form-switch"><input type="hidden" name="test_mode" value="0"><input class="form-check-input" id="test-{{ $gateway->id }}" type="checkbox" name="test_mode" value="1" @checked($gateway->test_mode)><label class="form-check-label" for="test-{{ $gateway->id }}">Test / sandbox mode</label></div></div>
<div class="profile-form-grid mt-3"><div><label class="form-label">Display name</label><input class="form-control" name="name" required value="{{ $gateway->name }}"></div><div><label class="form-label">Accepted currencies</label><input class="form-control" name="currencies" required value="{{ implode(', ', $gateway->currencies ?? []) }}" placeholder="USD, EUR, INR"></div>
@foreach($credentialFields as $key=>$label)<div><label class="form-label">{{ $label }}</label><input class="form-control" name="credentials[{{ $key }}]" type="{{ str_contains($key,'secret') || str_contains($key,'number') ? 'password':'text' }}" placeholder="{{ isset(($gateway->credentials??[])[$key]) ? 'Saved — leave blank to keep' : 'Not configured' }}" autocomplete="new-password"></div>@endforeach
@if($gateway->provider!=='bank_transfer')<div class="profile-span"><label class="form-label">Webhook signing secret</label><input class="form-control" name="webhook_secret" type="password" placeholder="{{ $gateway->webhook_secret ? 'Saved — leave blank to keep':'Not configured' }}" autocomplete="new-password"><div class="form-text">Endpoint: <code>{{ route('payments.webhook',$gateway->provider) }}</code></div></div>@else<div class="profile-span"><label class="form-label">Customer payment instructions</label><textarea class="form-control" name="instructions" rows="3">{{ $gateway->instructions }}</textarea></div>@endif
<div><label class="form-label">Percentage fee</label><div class="input-group"><input class="form-control" name="percentage_fee" type="number" min="0" max="100" step="0.001" value="{{ $gateway->percentage_fee }}"><span class="input-group-text">%</span></div></div><div><label class="form-label">Fixed fee</label><input class="form-control" name="fixed_fee" type="number" min="0" step="0.01" value="{{ $gateway->fixed_fee }}"></div><div><label class="form-label">Minimum amount</label><input class="form-control" name="minimum_amount" type="number" min="0" step="0.01" value="{{ $gateway->minimum_amount }}"></div><div><label class="form-label">Maximum amount</label><input class="form-control" name="maximum_amount" type="number" min="0" step="0.01" value="{{ $gateway->maximum_amount }}"></div><div><label class="form-label">Display order</label><input class="form-control" name="position" type="number" min="0" value="{{ $gateway->position }}"></div></div>
<div class="gateway-methods"><strong>Payment methods</strong><div>@foreach($gateway->methods as $method)<label class="form-check"><input type="hidden" name="methods[{{ $method->id }}]" value="0"><input class="form-check-input" type="checkbox" name="methods[{{ $method->id }}]" value="1" @checked($method->is_enabled)><span>{{ $method->name }}</span></label>@endforeach</div></div>
<button class="btn btn-portal w-100 mt-3" type="submit"><i class="bi bi-shield-check"></i> Save {{ $gateway->name }}</button></form>
@endforeach
</div><div class="alert alert-warning mt-4"><i class="bi bi-lock me-1"></i>Gateway credentials and webhook secrets are encrypted in the database. Always test in sandbox mode before accepting live payments.</div>
@endsection
