<?php
use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;
return new class extends Migration {
 public function up(): void {
  foreach(['job_sectors','job_specializations','job_titles'] as $name)Schema::create($name,function(Blueprint $t)use($name){$t->id();if($name==='job_specializations')$t->foreignId('job_sector_id')->constrained()->restrictOnDelete();if($name==='job_titles')$t->foreignId('job_specialization_id')->constrained()->restrictOnDelete();$t->string('code',40)->unique();$t->string('short_name',80)->nullable();$t->string('display_name',150);$t->text('description')->nullable();$t->unsignedInteger('sort_order')->default(0);$t->boolean('is_active')->default(true)->index();$t->timestamps();$t->softDeletes();});
  Schema::create('job_search_profiles',function(Blueprint $t){$t->id();$t->foreignId('user_id')->unique()->constrained()->cascadeOnDelete();$t->string('profile_type',20)->index();$t->string('headline')->nullable();$t->text('summary')->nullable();$t->unsignedSmallInteger('min_experience_years')->default(0);$t->unsignedSmallInteger('max_experience_years')->nullable();$t->decimal('min_annual_salary',14,2)->nullable();$t->decimal('max_annual_salary',14,2)->nullable();$t->char('currency',3)->default('INR');$t->json('preferred_locations')->nullable();$t->boolean('location_flexible')->default(false);$t->boolean('salary_negotiable')->default(false);$t->boolean('is_active')->default(true);$t->timestamps();});
  foreach(['job_title','skill','employment_type','work_mode','qualification_level'] as $relation)Schema::create("job_search_profile_{$relation}",function(Blueprint $t)use($relation){$t->id();$t->foreignId('job_search_profile_id')->constrained()->cascadeOnDelete();$t->foreignId("{$relation}_id")->constrained("{$relation}s")->restrictOnDelete();$t->unique(['job_search_profile_id',"{$relation}_id"]);});
  $now=now();$sectorIds=[];foreach(['FINANCE'=>'Financial Services','EDUCATION'=>'Education','TECHNOLOGY'=>'Information Technology','HEALTHCARE'=>'Healthcare','RETAIL'=>'Retail & Commerce','MANUFACTURING'=>'Manufacturing'] as $code=>$name)$sectorIds[$code]=DB::table('job_sectors')->insertGetId(compact('code')+['display_name'=>$name,'sort_order'=>count($sectorIds)*10+10,'is_active'=>true,'created_at'=>$now,'updated_at'=>$now]);
  $specs=[['BANKING','Banking','FINANCE'],['INSURANCE','Insurance','FINANCE'],['HIGHER_EDUCATION','Higher Education','EDUCATION'],['SCHOOL_EDUCATION','School Education','EDUCATION'],['SOFTWARE','Software Development','TECHNOLOGY'],['IT_SUPPORT','IT Support','TECHNOLOGY'],['CLINICAL','Clinical Services','HEALTHCARE']];$specIds=[];foreach($specs as $i=>[$code,$name,$sector])$specIds[$code]=DB::table('job_specializations')->insertGetId(['job_sector_id'=>$sectorIds[$sector],'code'=>$code,'display_name'=>$name,'sort_order'=>($i+1)*10,'is_active'=>true,'created_at'=>$now,'updated_at'=>$now]);
  $titles=[['BANK_CLERK','Bank Clerk','BANKING'],['BANK_MANAGER','Bank Manager','BANKING'],['INSURANCE_ADVISOR','Insurance Advisor','INSURANCE'],['TEACHER','Teacher','SCHOOL_EDUCATION'],['ASSISTANT_TEACHER','Assistant Teacher','SCHOOL_EDUCATION'],['ASSISTANT_PROFESSOR','Assistant Professor','HIGHER_EDUCATION'],['LECTURER','Lecturer','HIGHER_EDUCATION'],['SOFTWARE_DEVELOPER','Software Developer','SOFTWARE'],['WEB_DEVELOPER','Web Developer','SOFTWARE'],['IT_SUPPORT_EXECUTIVE','IT Support Executive','IT_SUPPORT'],['NURSE','Nurse','CLINICAL']];foreach($titles as $i=>[$code,$name,$spec])DB::table('job_titles')->insert(['job_specialization_id'=>$specIds[$spec],'code'=>$code,'display_name'=>$name,'sort_order'=>($i+1)*10,'is_active'=>true,'created_at'=>$now,'updated_at'=>$now]);
  foreach([['career','career-workspace','Job Preferences','job-preferences','talent.job-preferences.edit','bi-sliders2'],['recruitment','hiring-workspace','Candidate Search','candidate-search','recruiter.candidate-search.edit','bi-person-bounding-box']] as [$module,$parent,$name,$slug,$route,$icon]){$moduleId=DB::table('portal_modules')->where('slug',$module)->value('id');if(!$moduleId)continue;$parentId=DB::table('portal_menus')->where('slug',$parent)->value('id');$menuId=DB::table('portal_menus')->insertGetId(['portal_module_id'=>$moduleId,'parent_id'=>$parentId,'name'=>$name,'slug'=>$slug,'route_name'=>$route,'icon'=>$icon,'position'=>15,'is_active'=>true,'created_at'=>$now,'updated_at'=>$now]);foreach(DB::table('subscription_plans')->where('category',$module==='career'?'talent':'recruiter')->get() as $plan)DB::table('portal_menu_subscription_plan')->insert(['subscription_plan_id'=>$plan->id,'portal_menu_id'=>$menuId,'can_view'=>true,'can_create'=>true,'can_update'=>true,'can_delete'=>false,'created_at'=>$now,'updated_at'=>$now]);}
 }
 public function down():void{DB::table('portal_menus')->whereIn('slug',['job-preferences','candidate-search'])->delete();foreach(['qualification_level','work_mode','employment_type','skill','job_title'] as $r)Schema::dropIfExists("job_search_profile_{$r}");Schema::dropIfExists('job_search_profiles');Schema::dropIfExists('job_titles');Schema::dropIfExists('job_specializations');Schema::dropIfExists('job_sectors');}
};
