@extends('layouts.administrator')
@section('title', 'Permission Control Center')
@section('content')
<div class="dashboard-heading permission-dashboard-heading">
    <div><span class="dashboard-kicker">ACCESS CONTROL CENTER</span><h1>Good {{ now()->hour < 12 ? 'morning' : (now()->hour < 18 ? 'afternoon' : 'evening') }}, {{ Str::before(auth()->user()->name, ' ') }}.</h1><p>Manage role templates, individual access, and permission history from one place.</p></div>
    <div class="dashboard-actions"><a class="btn btn-portal-light" href="{{ route('admin.permission-audit') }}"><i class="bi bi-clock-history"></i><span>Audit log</span></a><a class="btn btn-portal" href="{{ route('admin.roles.index') }}"><i class="bi bi-person-gear"></i><span>Manage roles</span></a></div>
</div>

<section class="permission-hero mb-4">
    <div><span class="permission-hero-kicker"><i class="bi bi-shield-check"></i> Permission workflow</span><h2>Simple by design, accountable by default.</h2><p>Start with a category role, copy it to a user, then tailor only where needed. Every administrative change is recorded.</p></div>
    <div class="permission-flow" aria-label="Permission management workflow">
        @foreach([['1','Create role','Reusable template','bi-person-badge'],['2','Assign user','Copy permissions','bi-person-check'],['3','Customize','Individual override','bi-sliders'],['4','Audit','Review history','bi-clock-history']] as [$number,$title,$copy,$icon])
            <a href="{{ $number === '2' || $number === '3' ? route('admin.accounts.index') : ($number === '4' ? route('admin.permission-audit') : route('admin.roles.index')) }}"><span><i class="bi {{ $icon }}"></i><b>{{ $number }}</b></span><div><strong>{{ $title }}</strong><small>{{ $copy }}</small></div><i class="bi bi-chevron-right"></i></a>
        @endforeach
    </div>
</section>

<div class="row g-3 g-xl-4 metric-row">
    @foreach([['Active roles',$permissionStats['roles'],'Across 3 user categories','bi-person-badge','violet'],['Role assigned',$permissionStats['assigned'],'Users with a permission snapshot','bi-person-check','cyan'],['Customized users',$permissionStats['customized'],'Individual overrides recorded','bi-sliders','orange'],['Needs attention',$permissionStats['attention'],'Missing or inactive role','bi-exclamation-diamond','green']] as [$label,$value,$note,$icon,$tone])
        <div class="col-sm-6 col-xl-3"><a class="metric-card permission-metric" href="{{ $label === 'Active roles' ? route('admin.roles.index') : route('admin.accounts.index') }}"><div class="metric-top"><span class="metric-icon {{ $tone }}"><i class="bi {{ $icon }}"></i></span><i class="bi bi-arrow-up-right"></i></div><strong>{{ number_format($value) }}</strong><span>{{ $label }}</span><small>{{ $note }}</small></a></div>
    @endforeach
</div>

<div class="row g-4 mt-1">
    <div class="col-xl-7"><section class="dashboard-card h-100"><div class="card-heading"><div><span>ROLE LIBRARY</span><h2>Roles by user category</h2></div><a class="text-button" href="{{ route('admin.roles.index') }}">Manage templates <i class="bi bi-arrow-right"></i></a></div><div class="dashboard-role-groups">
        @foreach(\App\Enums\UserCategory::cases() as $category)<div class="dashboard-role-group"><div class="dashboard-role-title"><span><i class="bi {{ $category === \App\Enums\UserCategory::Administrator ? 'bi-shield-lock' : ($category === \App\Enums\UserCategory::Recruiter ? 'bi-building' : 'bi-briefcase') }}"></i></span><div><strong>{{ $category->label() }}</strong><small>{{ ($rolesByCategory[$category->value] ?? collect())->count() }} role templates</small></div></div><div class="dashboard-role-list">@foreach($rolesByCategory[$category->value] ?? [] as $role)<a href="{{ $role->is_super_admin ? route('admin.roles.index') : route('admin.roles.edit',$role) }}"><span>{{ mb_substr($role->name,0,1) }}</span><div><strong>{{ $role->name }}</strong><small>{{ $role->users_count }} {{ Str::plural('user',$role->users_count) }}</small></div>@if($role->is_super_admin)<b>FULL</b>@else<i class="bi bi-chevron-right"></i>@endif</a>@endforeach</div></div>@endforeach
    </div></section></div>
    <div class="col-xl-5"><section class="dashboard-card h-100"><div class="card-heading"><div><span>PERMISSION COVERAGE</span><h2>Configuration health</h2></div><span class="status-chip {{ $permissionStats['attention'] ? 'muted' : 'success' }}"><i></i>{{ $permissionStats['attention'] ? 'Review needed' : 'Healthy' }}</span></div><div class="permission-health"><div class="permission-health-ring" style="--health:{{ $permissionStats['assigned'] ? round((($permissionStats['assigned']-$permissionStats['attention'])/$permissionStats['assigned'])*100) : 100 }}%"><strong>{{ $permissionStats['assigned'] ? max(0,round((($permissionStats['assigned']-$permissionStats['attention'])/$permissionStats['assigned'])*100)) : 100 }}%</strong><small>role coverage</small></div><div><div><span>Modules governed</span><strong>{{ $coverage['modules'] }}</strong></div><div><span>Menu policies</span><strong>{{ $coverage['menus'] }}</strong></div><div><span>Individual overrides</span><strong>{{ $permissionStats['customized'] }}</strong></div></div></div><a class="permission-review-cta" href="{{ route('admin.accounts.index', ['status'=>'pending_review']) }}"><i class="bi bi-search"></i><div><strong>Review user access</strong><small>Find unassigned, restricted, or customized accounts</small></div><i class="bi bi-arrow-right"></i></a></section></div>
</div>

<div class="row g-4 mt-1">
    <div class="col-xl-7"><section class="dashboard-card"><div class="card-heading"><div><span>ACCOUNT ACCESS</span><h2>Recently added users</h2></div><a class="text-button" href="{{ route('admin.accounts.index') }}">Review all <i class="bi bi-arrow-right"></i></a></div><div class="table-responsive"><table class="table portal-table align-middle"><thead><tr><th>User</th><th>Category</th><th>Role</th><th>Permission source</th><th></th></tr></thead><tbody>@foreach($recentUsers as $member)<tr><td><div class="member-cell"><span>{{ mb_substr($member->name,0,1) }}</span><div><strong>{{ $member->name }}</strong><small>{{ $member->email }}</small></div></div></td><td>{{ $member->userType?->category->label() }}</td><td>{{ $member->role?->name ?? 'Unassigned' }}</td><td><span class="permission-source {{ $member->permissions_customized_at ? 'custom' : '' }}"><i class="bi {{ $member->permissions_customized_at ? 'bi-sliders' : 'bi-copy' }}"></i>{{ $member->permissions_customized_at ? 'Customized' : 'Role snapshot' }}</span></td><td><a class="table-action" href="{{ route('admin.accounts.show',$member->id) }}"><i class="bi bi-chevron-right"></i></a></td></tr>@endforeach</tbody></table></div></section></div>
    <div class="col-xl-5"><section class="dashboard-card"><div class="card-heading"><div><span>RECENT CHANGES</span><h2>Permission audit</h2></div><a class="text-button" href="{{ route('admin.permission-audit') }}">Full log <i class="bi bi-arrow-right"></i></a></div><div class="permission-audit-feed">@forelse($recentAudits as $audit)<div><span class="audit-event-icon"><i class="bi {{ str_contains($audit->event,'role') ? 'bi-person-badge' : 'bi-sliders' }}"></i></span><div><strong>{{ $audit->summary }}</strong><small>{{ $audit->actor?->name ?? 'System' }} · {{ $audit->created_at->diffForHumans() }}</small></div></div>@empty<div class="account-empty py-4"><i class="bi bi-journal-check"></i><strong>No permission changes recorded</strong></div>@endforelse</div></section></div>
</div>
@endsection
