@extends('layouts.recruiter')
@section('title', 'Recruiter Dashboard')
@section('content')
    <div class="dashboard-heading"><div><span class="dashboard-kicker">RECRUITMENT OVERVIEW</span><h1>Build your next great team.</h1><p>Track opportunities, review promising talent, and keep every conversation moving.</p></div><div class="dashboard-actions"><button class="btn btn-portal-light"><i class="bi bi-upload"></i><span>Import talent</span></button><button class="btn btn-portal"><i class="bi bi-plus-lg"></i><span>Post a job</span></button></div></div>
    <div class="row g-3 g-xl-4 metric-row">
        @foreach([['Active jobs','8','2 closing soon','bi-megaphone','orange'],['New applications','42','+18% this week','bi-inboxes','violet'],['Interviews','11','Next 7 days','bi-camera-video','cyan'],['Offers sent','5','3 awaiting reply','bi-send-check','green']] as [$label,$value,$note,$icon,$tone])
            <div class="col-sm-6 col-xl-3"><article class="metric-card"><div class="metric-top"><span class="metric-icon {{ $tone }}"><i class="bi {{ $icon }}"></i></span><button><i class="bi bi-three-dots"></i></button></div><strong>{{ $value }}</strong><span>{{ $label }}</span><small><i class="bi bi-arrow-up-right"></i>{{ $note }}</small></article></div>
        @endforeach
    </div>
    <div class="row g-4 mt-1">
        <div class="col-xl-8"><article class="dashboard-card h-100"><div class="card-heading"><div><span>HIRING PIPELINE</span><h2>Talent by stage</h2></div><button class="text-button">View pipeline <i class="bi bi-arrow-right"></i></button></div><div class="pipeline-grid">@foreach([['Applied',64,100,'violet'],['Screening',38,72,'cyan'],['Interview',21,48,'orange'],['Offer',8,24,'green']] as [$stage,$count,$width,$tone])<div class="pipeline-item"><div><span>{{ $stage }}</span><strong>{{ $count }}</strong></div><div class="pipeline-track"><i class="{{ $tone }}" style="width:{{ $width }}%"></i></div><small>{{ round($count / 64 * 100) }}% of applicants</small></div>@endforeach</div><div class="pipeline-summary"><div><strong>131</strong><span>Total candidates</span></div><div><strong>18 days</strong><span>Avg. time to hire</span></div><div><strong>74%</strong><span>Response rate</span></div></div></article></div>
        <div class="col-xl-4"><article class="dashboard-card h-100"><div class="card-heading"><div><span>TODAY</span><h2>Interview schedule</h2></div><span class="date-chip">{{ now()->format('M d') }}</span></div><div class="schedule-list">@foreach([['09:30','Maya Chen','Product Designer','purple'],['11:00','Noah Williams','Backend Engineer','orange'],['14:30','Ava Patel','Growth Associate','cyan']] as [$time,$name,$role,$tone])<div class="schedule-item"><time>{{ $time }}</time><span class="schedule-line {{ $tone }}"></span><span class="candidate-avatar {{ $tone }}">{{ collect(explode(' ',$name))->map(fn($w)=>$w[0])->implode('') }}</span><div><strong>{{ $name }}</strong><small>{{ $role }}</small></div><button><i class="bi bi-camera-video"></i></button></div>@endforeach</div><button class="btn btn-portal-soft w-100 mt-3">Open calendar</button></article></div>
    </div>
    <div class="row g-4 mt-1"><div class="col-12"><article class="dashboard-card"><div class="card-heading"><div><span>RECOMMENDED</span><h2>Talent worth meeting</h2></div><button class="text-button">Explore all talent <i class="bi bi-arrow-right"></i></button></div><div class="candidate-grid">@foreach([['Sophia Kim','Senior UX Designer','94','SK'],['Liam Carter','Full-stack Engineer','91','LC'],['Amelia Brown','Marketing Strategist','88','AB']] as [$name,$role,$match,$initials])<div class="candidate-card"><div class="candidate-card-top"><span class="candidate-avatar large">{{ $initials }}</span><button><i class="bi bi-bookmark"></i></button></div><strong>{{ $name }}</strong><span>{{ $role }}</span><div class="candidate-tags"><small>Remote</small><small>5+ years</small></div><div class="match-row"><span><i class="bi bi-stars"></i>{{ $match }}% match</span><button class="btn btn-sm btn-portal-soft">View profile</button></div></div>@endforeach</div></article></div></div>
@endsection
