@extends('layouts.talent')
@section('title', 'Talent Dashboard')
@section('content')
    <div class="dashboard-heading"><div><span class="dashboard-kicker">MY CAREER</span><h1>Your next opportunity is closer.</h1><p>Keep your profile fresh, discover thoughtful matches, and follow every application.</p></div><div class="dashboard-actions"><button class="btn btn-portal-light"><i class="bi bi-eye"></i><span>Preview profile</span></button><button class="btn btn-portal"><i class="bi bi-search"></i><span>Explore jobs</span></button></div></div>
    <div class="row g-4">
        <div class="col-xl-8"><article class="profile-hero dashboard-card"><div class="profile-hero-copy"><span class="dashboard-kicker">PROFILE STRENGTH</span><h2>You’re making a strong impression.</h2><p>Add your latest project to stand out in more recruiter searches.</p><div class="profile-progress"><div><span>86% complete</span><span>Excellent</span></div><div class="progress"><div class="progress-bar" style="width:86%"></div></div></div><button class="btn btn-portal">Complete my profile</button></div><div class="profile-score-ring"><strong>86</strong><small>profile score</small></div></article></div>
        <div class="col-xl-4"><article class="dashboard-card h-100"><div class="card-heading"><div><span>THIS WEEK</span><h2>Your momentum</h2></div></div><div class="momentum-grid"><div><i class="bi bi-eye"></i><strong>28</strong><span>Profile views</span><small>+12%</small></div><div><i class="bi bi-search-heart"></i><strong>16</strong><span>Recruiter searches</span><small>+8%</small></div><div><i class="bi bi-bookmark-check"></i><strong>7</strong><span>Saved roles</span><small>2 new</small></div><div><i class="bi bi-chat-heart"></i><strong>3</strong><span>Messages</span><small>Reply soon</small></div></div></article></div>
    </div>
    <div class="row g-4 mt-1">
        <div class="col-xl-8"><article class="dashboard-card"><div class="card-heading"><div><span>MADE FOR YOU</span><h2>Fresh job matches</h2></div><button class="text-button">See all jobs <i class="bi bi-arrow-right"></i></button></div><div class="job-match-list">@foreach([['Arc & Co.','Product Designer','Remote · Full time','96','A','purple'],['Northstar Labs','UX Researcher','Hybrid · Full time','92','N','cyan'],['Bloom Studio','Design Systems Lead','Remote · Contract','88','B','orange']] as [$company,$role,$meta,$match,$logo,$tone])<div class="job-match"><span class="company-avatar {{ $tone }}">{{ $logo }}</span><div class="job-copy"><strong>{{ $role }}</strong><span>{{ $company }}</span><small>{{ $meta }}</small></div><span class="match-pill"><i class="bi bi-stars"></i>{{ $match }}%</span><button><i class="bi bi-bookmark"></i></button></div>@endforeach</div></article></div>
        <div class="col-xl-4"><article class="dashboard-card h-100"><div class="card-heading"><div><span>APPLICATIONS</span><h2>Recent progress</h2></div></div><div class="application-timeline">@foreach([['Interview scheduled','Nova Labs','Today','complete'],['Application reviewed','Helio Works','Yesterday','complete'],['Application sent','Arc & Co.','3 days ago','current']] as [$event,$company,$date,$state])<div class="timeline-item {{ $state }}"><i></i><div><strong>{{ $event }}</strong><span>{{ $company }}</span><small>{{ $date }}</small></div></div>@endforeach</div><button class="btn btn-portal-soft w-100">Track all applications</button></article></div>
    </div>
@endsection
